name: LLVM

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        llvm: [10.0.1]
    steps:
      - name: Prepare build
        run: mkdir llvm/build llvm/src

      - name: Clone LLVM
        uses: actions/checkout@v2
        with:
          repository: llvm/llvm-project
          ref: llvmorg-${{ matrix.llvm}}
          path: llvm/src
      
      - name: Build A
        run: |
              cmake `
              -S "src" `
              -B "buid" `
              -G "Visual Studio 16 2019" `
              -Thost=x64 `
              -A x64 `
              -DLLVM_ENABLE_PROJECTS="lld;clang" `
              -DCMAKE_BUILD_TYPE=Release `
              -DCMAKE_INSTALL_PREFIX="$install_dir" 
        working-directory: llvm
      
      - name: Build B
        run: cmake --build "build" --target INSTALL --config Release
        working-directory: llvm/build
