name: LLVM

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        llvm: [10.0.1]
    timeout-minutes: 300
    steps:
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Prepare build
        run: mkdir -p llvm/build && mkdir -p llvm/src

      - name: Clone LLVM
        uses: actions/checkout@v2
        with:
          repository: llvm/llvm-project
          ref: llvmorg-${{ matrix.llvm}}
          path: llvm/src

      - name: Configure
        run: |
              cmake `
              -G Ninja `
              -S "src/llvm" `
              -B "build" `
              -DLLVM_ENABLE_PROJECTS="lld;clang" `
              -DCMAKE_BUILD_TYPE=Release `
              -DLLVM_INCLUDE_EXAMPLES=OFF `
              -DLLVM_INCLUDE_DOCS=OFF `
              -DLLVM_INCLUDE_TESTS=OFF `
              -DLLVM_INCLUDE_GO_TESTS=OFF `
              -DLLVM_INCLUDE_TOOLS=ON `
              -DLLVM_INCLUDE_UTILS=OFF `
              -DLLVM_OPTIMIZED_TABLEGEN=ON `
        working-directory: llvm
        timeout-minutes: 30
      
      - name: Build
        run: cmake --build . --config Release
        working-directory: llvm/build
        timeout-minutes: 300

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.llvm }}
          path: llvm/build
          if-no-files-found: error
          retention-days: 1
