name: LLVM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install llvmenv
        run: cargo install llvmenv
      - name: Init LLVMENV
        run: llvmenv init
      - name: Build LLVM 10.0.0
        run: llvmenv build-entry 10.0.0
