name: LLVM

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install llvmenv
        uses: actions-rs/install@v0.1
        with:
          crate: llvmenv
          version: latest
      - name: Init LLVMENV
        run: llvmenv init
      - name: Build LLVM 10.0.0
        run: llvmenv build-entry 10.0.0
