name: LLVM

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Clone LLVM 10.0.1
        uses: actions/checkout@v2.3.4
        with:
          repository: llvm/llvm-project
          ref: llvmorg-10.0.1
          path: llvmorg-10.0.1
      
      - name: Prepare build
        run: mkdir build
        working-directory: llvmorg-10.0.1
      
      - name: Build A
        run: cmake -G "Visual Studio 16 2019" ../llvm
        working-directory: llvmorg-10.0.1/build
      
      - name: Build B
        run: cmake --build .
        working-directory: llvmorg-10.0.1/build
